BLACK    = (   0,   0,   0)
WHITE    = ( 255, 255, 255)
GREEN    = (   0, 255,   0)
RED      = ( 255,   0,   0)
BLUE     = (   0,   0, 255)
NAVY     = (   0,   0, 127)
VIOLET   = ( 255,   0, 255)
PINK     = ( 255, 180, 180)
YELLOW   = ( 255, 255,   0)
GRAY     = ( 100, 100, 100)
LIGHTGRAY= ( 200, 200, 200)
ORANGE   = ( 255, 127,   0)
TRANS    = (   1,   2,   3)

WIDTH = 770
HEIGHT = 770
STATUS_BAR_HEIGHT = 20
STATUS_BAR_COLOR = BLACK
FRAME_RATE = 60
WELCOME_MESSAGE = 'Welcome to Minesweeper! Choose a level'
WIN_MESSAGE = 'You win! Press ENTER to return to the menu.'
DEAD_MESSAGE = 'Oops! You hit a mine. Press ENTER to return to menu.'
INTRO_BACKGROUND = NAVY
POSTGAME_BACKGROUND = YELLOW
TEXT_COLOR = WHITE
MAIN_TEXT_FONT = 'Calibri'
MAIN_TEXT_SIZE = 30
STATUS_TEXT_FONT = 'Calibri'
STATUS_TEXT_SIZE = 15
WALL_CHAR = 'x'
HALLWAY_CHAR = ' '
GAME_TITLE = 'Minesweeper'
PLAYER_CHAR = '@'
FINISH_CHAR = '$'
HIDDEN_CHAR = ' '
HIDDEN_COLOR = WHITE
LINE_COLOR = BLACK
LINE_THICKNESS = 3
ERROR_CHAR = '!'
BEST_TIMES_FILE = 'best_times.txt'