BLACK    = (   0,   0,   0)
WHITE    = ( 255, 255, 255)
GREEN    = (   0, 255,   0)
RED      = ( 255,   0,   0)
BLUE     = (   0,   0, 255)
NAVY     = (   0,   0, 127)
VIOLET   = ( 255,   0, 255)
PINK     = ( 255, 180, 180)
YELLOW   = ( 255, 255,   0)
GRAY     = ( 100, 100, 100)
LIGHTGRAY= ( 200, 200, 200)
ORANGE   = ( 255, 127,   0)
TRANS    = (   1,   2,   3)

WIDTH = 800
HEIGHT = 800
FRAME_RATE = 60
PLAYER_COLOR = GREEN
FINISH_COLOR = RED
HALLWAY_COLOR = BLUE
WALL_COLOR = BLACK
WELCOME_MESSAGE = 'Welcome to Minesweeper! Press ENTER to play.'
WIN_MESSAGE = 'You win! Press ENTER to return to the menu.'
DEAD_MESSAGE = 'Oops! You hit a mine. Press ENTER to return to the menu.'
INTRO_BACKGROUND = BLUE
POSTGAME_BACKGROUND = YELLOW
TEXT_COLOR = WHITE
TEXT_FONT = 'Calibri'
TEXT_SIZE = 30
WALL_CHAR = 'x'
HALLWAY_CHAR = ' '
GAME_TITLE = 'Minesweeper'
PLAYER_CHAR = '@'
FINISH_CHAR = '$'
HIDDEN_CHAR = ' '
HIDDEN_COLOR = WHITE
LINE_COLOR = BLACK
LINE_THICKNESS = 3
ERROR_CHAR = '!'